### ISSUE TITLE
修正進度報告顯示邏輯

### ISSUE THREAD

**Issue by aszx87410** [Lidemy/lidemy-learning-frontend#14]
基本上是後端要改，如果有勾選「進度相近的話」，目前的邏輯是會篩選「所有人」的進度
但會變成老師或是助教 po 的都看不到
所以應該改成：「如果是第四期才進度相近，否則的話都顯示」

**Comment by ishin4554** [comment]
ref: https://github.com/Lidemy/lidemy-learning-backend/issues/13
