### ISSUE TITLE
手機版批改與作業區 RWD 

### ISSUE THREAD

**Issue by ishin4554** [Lidemy/lidemy-learning-frontend#27]
手機版 Table RWD 破版 TAT

**Comment by aszx87410** [comment]
哭哭 因為我之前調的時候只注意到桌面版QQ

**Comment by aszx87410** [comment]
順手修掉了，螢幕寬度小於 1000 就設成 1000，否則設定成 100%

**Comment by aszx87410** [comment]
https://github.com/Lidemy/lidemy-learning-frontend/commit/a3644eff90bc87d48ea5e23e9e98c4d0e77553f2
